import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { useUser } from '@/lib/store';
import { motion } from 'framer-motion';
import { ArrowLeft, Calendar as CalendarIcon, Clock, MapPin, Plus, Check, X, Sparkles, Loader, Star, List, LayoutGrid, Navigation, GripVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { GenerateItineraryModal } from '@/components/generate-itinerary-modal';

interface Activity {
  id: string;
  time: string;
  title: string;
  location: string;
  address?: string;
  yelpBusinessId?: string;
  rating?: number;
  price?: string;
  image_url?: string;
  categories?: string[];
  completed: boolean;
  travelTimeFromPrevious?: number;
  slotType?: string;
  coordinates?: { latitude: number; longitude: number };
}

interface DayPlan {
  date: string;
  activities: Activity[];
}

export default function TripPlanner() {
  const [, setLocation] = useLocation();
  const { profile, sessionId } = useUser();
  const [days, setDays] = useState<DayPlan[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [numDays, setNumDays] = useState(3);
  const [cachedBusinesses, setCachedBusinesses] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'calendar' | 'list'>('calendar');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [draggedActivity, setDraggedActivity] = useState<{ dayIndex: number; activityId: string } | null>(null);
  const [addActivityModal, setAddActivityModal] = useState<{ open: boolean; dayIndex: number | null }>({ open: false, dayIndex: null });
  const [newActivity, setNewActivity] = useState({ title: '', time: '9:00 AM', location: '' });
  const [showRegenerateModal, setShowRegenerateModal] = useState(false);
  const [activityMode, setActivityMode] = useState<'saved' | 'custom'>('saved');
  const [selectedBusiness, setSelectedBusiness] = useState<any>(null);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!profile.isOnboarded) {
      setLocation('/dashboard');
    }
  }, [profile.isOnboarded, setLocation]);

  // Load saved itinerary on mount
  useEffect(() => {
    const loadSavedItinerary = async () => {
      if (!sessionId || !profile.currentTripId) return;
      
      try {
        const response = await fetch(`/api/trips/${profile.currentTripId}/itinerary`, {
          headers: {
            'x-session-id': sessionId,
          },
        });
        
        if (response.ok) {
          const data = await response.json();
          if (data.itinerary && data.itinerary.length > 0) {
            setDays(data.itinerary);
            // Recalculate travel times after loading to ensure accuracy
            setTimeout(() => recalculateTravelTimes(), 100);
          }
        }
      } catch (err) {
        console.error('Failed to load saved itinerary:', err);
      }
    };

    loadSavedItinerary();
  }, [sessionId, profile.currentTripId]);

  // Auto-save itinerary when days change
  useEffect(() => {
    const saveItinerary = async () => {
      if (!sessionId || !profile.currentTripId || days.length === 0) return;
      
      try {
        await fetch(`/api/trips/${profile.currentTripId}/itinerary`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-session-id': sessionId,
          },
          body: JSON.stringify({ itinerary: days }),
        });
      } catch (err) {
        console.error('Failed to save itinerary:', err);
      }
    };

    // Debounce save to avoid too many requests
    const timeoutId = setTimeout(saveItinerary, 1000);
    return () => clearTimeout(timeoutId);
  }, [days, sessionId, profile.currentTripId]);

  // Check for auto-generate URL params
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const autoGenerate = params.get('autoGenerate') === 'true';
    const daysParam = params.get('days');
    
    if (autoGenerate && !hasAutoGenerated && cachedBusinesses.length > 0) {
      if (daysParam) {
        setNumDays(parseInt(daysParam) || 3);
      }
      setHasAutoGenerated(true);
      // Trigger generation after a short delay to ensure state is set
      setTimeout(() => generateItinerary(), 100);
    }
  }, [cachedBusinesses, hasAutoGenerated]);

  // Fetch Yelp data on mount with full user profile (same as dashboard)
  useEffect(() => {
    const fetchYelpData = async () => {
      if (!profile.country || !sessionId) return;
      
      try {
        // Build comprehensive search params with full user profile
        const searchParams = new URLSearchParams({
          location: profile.country,
          term: 'restaurants',
          interests: profile.interests.join(','),
          limit: '50',
          travelingWithKids: String(profile.travelingWithKids || false),
          kidsAges: (profile.kidsAges || []).join(','),
          groupSize: String((profile.companions?.length || 0) + 1),
          companionAges: profile.companions?.map(c => c.age).filter(Boolean).join(',') || '',
          userAge: String(profile.age || 30),
        });
        
        const response = await fetch(`/api/yelp/search?${searchParams.toString()}`);
        if (response.ok) {
          const data = await response.json();
          setCachedBusinesses(data.businesses || []);
        }
      } catch (err) {
        console.error('Failed to fetch Yelp data:', err);
      }
    };

    fetchYelpData();
  }, [profile.country, sessionId, profile.interests, profile.travelingWithKids, profile.kidsAges, profile.companions, profile.age]);

  const generateItinerary = async (daysToGenerate?: number) => {
    console.log('generateItinerary called with:', daysToGenerate);
    if (!sessionId) {
      console.error('No session ID');
      return;
    }

    if (cachedBusinesses.length === 0) {
      setError('No places available. Please go back to the dashboard and search for places first.');
      return;
    }

    const finalNumDays = daysToGenerate || numDays;
    console.log('Final num days:', finalNumDays);
    setIsGenerating(true);
    setError(null);
    setShowRegenerateModal(false);
    
    try {
      const response = await fetch('/api/itinerary/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-session-id': sessionId,
        },
        body: JSON.stringify({
          tripId: profile.currentTripId,
          numDays: finalNumDays,
          location: profile.country,
          interests: profile.interests || [],
          // Only send essential data - strip out images and unnecessary fields
          businesses: (cachedBusinesses || []).map(b => ({
            id: b.id,
            name: b.name,
            rating: b.rating,
            price: b.price,
            categories: b.categories,
            coordinates: b.coordinates,
            location: b.location,
            image_url: b.image_url,
            review_count: b.review_count,
          })),
        }),
      });

      if (response.ok) {
        const data = await response.json();
        setDays(data.itinerary);
        setNumDays(finalNumDays);
        // Recalculate travel times after generation to ensure accuracy
        setTimeout(() => recalculateTravelTimes(), 100);
      } else {
        const errData = await response.json();
        setError(errData.error || 'Failed to generate itinerary');
      }
    } catch (err) {
      console.error('Error generating itinerary:', err);
      setError('Connection error. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleActivity = (dayIndex: number, activityId: string) => {
    setDays(prev => prev.map((day, idx) => {
      if (idx === dayIndex) {
        return {
          ...day,
          activities: day.activities.map(act => 
            act.id === activityId ? { ...act, completed: !act.completed } : act
          ),
        };
      }
      return day;
    }));
  };

  const removeActivity = (dayIndex: number, activityId: string) => {
    setDays(prev => prev.map((day, idx) => {
      if (idx === dayIndex) {
        return {
          ...day,
          activities: day.activities.filter(act => act.id !== activityId),
        };
      }
      return day;
    }));
  };

  const addDay = () => {
    setDays(prev => [...prev, {
      date: `Day ${prev.length + 1}`,
      activities: [],
    }]);
  };

  // Drag and drop handlers
  const handleDragStart = (dayIndex: number, activityId: string) => {
    setDraggedActivity({ dayIndex, activityId });
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (targetDayIndex: number, targetPosition: number) => {
    if (!draggedActivity) return;

    const { dayIndex: sourceDayIndex, activityId } = draggedActivity;
    
    setDays(prev => {
      const newDays = [...prev];
      const sourceDay = newDays[sourceDayIndex];
      const activityIndex = sourceDay.activities.findIndex(a => a.id === activityId);
      
      if (activityIndex === -1) return prev;
      
      const [movedActivity] = sourceDay.activities.splice(activityIndex, 1);
      
      if (sourceDayIndex === targetDayIndex) {
        // Moving within same day
        sourceDay.activities.splice(targetPosition, 0, movedActivity);
      } else {
        // Moving to different day
        newDays[targetDayIndex].activities.splice(targetPosition, 0, movedActivity);
      }
      
      return newDays;
    });
    
    setDraggedActivity(null);
    
    // Recalculate travel times after drop
    recalculateTravelTimes();
  };

  // Calculate distance between two coordinates using Haversine formula
  const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
    // Validate coordinates
    if (!isFinite(lat1) || !isFinite(lon1) || !isFinite(lat2) || !isFinite(lon2)) {
      return 0;
    }
    if (lat1 === lat2 && lon1 === lon2) {
      return 0;
    }
    
    const R = 6371; // Earth's radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = 
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c; // Distance in km
  };

  // Calculate walking time based on distance
  // Average walking speed: 5 km/h (about 3.1 mph)
  // Add 20% for real-world conditions (traffic lights, terrain, etc.)
  const calculateWalkingTime = (distanceKm: number): number => {
    if (distanceKm <= 0) return 0;
    
    const walkingSpeedKmh = 5; // Average walking speed
    const realWorldFactor = 1.2; // Account for stops, crossings, etc.
    const timeHours = (distanceKm / walkingSpeedKmh) * realWorldFactor;
    const timeMinutes = Math.round(timeHours * 60);
    
    // Return actual calculated time, min 1 minute for very close places
    return Math.max(1, Math.min(120, timeMinutes));
  };

  // Recalculate travel times for all activities
  const recalculateTravelTimes = () => {
    setDays(prev => prev.map(day => ({
      ...day,
      activities: day.activities.map((activity, idx) => {
        if (idx === 0) {
          return { ...activity, travelTimeFromPrevious: undefined };
        }
        
        const prevActivity = day.activities[idx - 1];
        
        // Check if both activities have valid coordinates
        const hasValidCoords = activity.coordinates && 
          prevActivity.coordinates &&
          isFinite(activity.coordinates.latitude) &&
          isFinite(activity.coordinates.longitude) &&
          isFinite(prevActivity.coordinates.latitude) &&
          isFinite(prevActivity.coordinates.longitude);
        
        if (hasValidCoords) {
          const distance = calculateDistance(
            prevActivity.coordinates!.latitude,
            prevActivity.coordinates!.longitude,
            activity.coordinates!.latitude,
            activity.coordinates!.longitude
          );
          const walkingTime = calculateWalkingTime(distance);
          // Only show travel time if there's actual distance
          return { ...activity, travelTimeFromPrevious: walkingTime > 0 ? walkingTime : undefined };
        }
        
        // No travel time if coordinates are missing
        return { ...activity, travelTimeFromPrevious: undefined };
      }),
    })));
  };

  // Add custom activity
  const handleAddActivity = () => {
    if (addActivityModal.dayIndex === null) return;

    let activity: Activity;

    if (activityMode === 'saved' && selectedBusiness) {
      // Add from saved Yelp location
      activity = {
        id: `saved-${Date.now()}`,
        time: newActivity.time,
        title: selectedBusiness.name,
        location: selectedBusiness.location?.city || profile.country,
        address: selectedBusiness.location?.display_address?.join(', '),
        yelpBusinessId: selectedBusiness.id,
        rating: selectedBusiness.rating,
        price: selectedBusiness.price,
        image_url: selectedBusiness.image_url,
        categories: selectedBusiness.categories?.map((c: any) => c.title),
        coordinates: selectedBusiness.coordinates,
        completed: false,
        slotType: 'Added',
      };
    } else if (activityMode === 'custom' && newActivity.title) {
      // Add custom activity
      activity = {
        id: `custom-${Date.now()}`,
        time: newActivity.time,
        title: newActivity.title,
        location: newActivity.location || profile.country,
        completed: false,
        slotType: 'Custom',
      };
    } else {
      return; // Invalid state
    }

    setDays(prev => prev.map((day, idx) => {
      if (idx === addActivityModal.dayIndex) {
        return {
          ...day,
          activities: [...day.activities, activity],
        };
      }
      return day;
    }));

    // Reset modal state
    setAddActivityModal({ open: false, dayIndex: null });
    setNewActivity({ title: '', time: '9:00 AM', location: '' });
    setSelectedBusiness(null);
    setSearchQuery('');
    setActivityMode('saved');
    
    // Recalculate travel times after adding
    setTimeout(() => recalculateTravelTimes(), 100);
  };

  const handleRegenerateClick = () => {
    setShowRegenerateModal(true);
  };

  const createManualItinerary = () => {
    const emptyDays = Array.from({ length: numDays }, (_, idx) => ({
      date: `Day ${idx + 1}`,
      activities: [],
    }));
    setDays(emptyDays);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white border-b border-border/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setLocation('/dashboard')}
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-xl font-bold">{profile.currentTripName || 'Trip Planner'}</h1>
              <p className="text-xs text-muted-foreground">{profile.country}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {days.length > 0 && (
              <Tabs value={viewMode} onValueChange={(v) => setViewMode(v as 'calendar' | 'list')}>
                <TabsList>
                  <TabsTrigger value="calendar" className="gap-2">
                    <LayoutGrid className="w-4 h-4" />
                    Calendar
                  </TabsTrigger>
                  <TabsTrigger value="list" className="gap-2">
                    <List className="w-4 h-4" />
                    List
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            )}
            
            <Button onClick={handleRegenerateClick} disabled={isGenerating} className="gap-2">
              {isGenerating ? (
                <>
                  <Loader className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  {days.length > 0 ? 'Regenerate' : 'Generate Itinerary'}
                </>
              )}
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        {/* AI Generation Section */}
        {days.length === 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center py-16"
          >
            <div className="max-w-2xl mx-auto">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6">
                <Sparkles className="w-8 h-8 text-primary" />
              </div>
              <h2 className="text-3xl font-bold mb-4">Smart Trip Planning</h2>
              <p className="text-muted-foreground mb-8">
                Create a personalized day-by-day itinerary based on Yelp's top-rated places,
                interests, and travel companions. We'll optimize routes, consider opening hours,
                and plan perfect meal times.
              </p>

              <div className="flex items-center justify-center gap-4 mb-8">
                <label className="text-sm font-medium">Number of days:</label>
                <Input
                  type="number"
                  min="1"
                  max="14"
                  value={numDays}
                  onChange={(e) => setNumDays(parseInt(e.target.value) || 3)}
                  className="w-20 text-center"
                />
              </div>

              {error && (
                <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
                  {error}
                </div>
              )}

              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Button
                  size="lg"
                  onClick={() => generateItinerary()}
                  disabled={isGenerating || cachedBusinesses.length === 0}
                  className="gap-2"
                >
                  {isGenerating ? (
                    <>
                      <Loader className="w-5 h-5 animate-spin" />
                      Building Your Itinerary...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-5 h-5" />
                      Generate {numDays}-Day Itinerary
                    </>
                  )}
                </Button>

                <Button
                  size="lg"
                  variant="outline"
                  onClick={createManualItinerary}
                  disabled={isGenerating}
                  className="gap-2"
                >
                  <Plus className="w-5 h-5" />
                  Create Manually
                </Button>
              </div>

              {cachedBusinesses.length > 0 && (
                <p className="text-sm text-muted-foreground mt-4">
                  Using {cachedBusinesses.length} places from Yelp in {profile.country}
                </p>
              )}
            </div>
          </motion.div>
        )}

        {/* Itinerary Days */}
        {days.length > 0 && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold">Your Itinerary</h2>
                <p className="text-sm text-muted-foreground">
                  {days.reduce((acc, day) => acc + day.activities.filter(a => a.completed).length, 0)} of{' '}
                  {days.reduce((acc, day) => acc + day.activities.length, 0)} activities completed
                </p>
              </div>
             
            </div>

            {/* Calendar View - Unified Timeline */}
            {viewMode === 'calendar' && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
              >
                <Card className="shadow-xl border-none overflow-hidden">
                  {/* Calendar Header */}
                  <div className="bg-linear-to-r from-primary to-primary/80 p-6">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <CalendarIcon className="w-8 h-8 text-white" />
                        <div className="text-white">
                          <h3 className="text-2xl font-bold">Trip Calendar</h3>
                          <p className="text-sm text-white/80 mt-1">
                            {days.length} days • {days.reduce((acc, day) => acc + day.activities.length, 0)} activities
                          </p>
                        </div>
                      </div>
                      <div className="text-white text-right">
                        <div className="text-3xl font-bold">
                          {days.reduce((acc, day) => acc + day.activities.filter(a => a.completed).length, 0)}
                        </div>
                        <div className="text-sm text-white/80">completed</div>
                      </div>
                    </div>
                  </div>

                  {/* Days Timeline */}
                  <div className="p-6 bg-gray-50">
                    <div className="space-y-8">
                      {days.map((day, dayIndex) => (
                        <motion.div
                          key={dayIndex}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: dayIndex * 0.1 }}
                          className="relative"
                        >
                          {/* Day Header */}
                          <div className="flex items-center gap-4 mb-4">
                            <div className="flex items-center gap-3 bg-white rounded-xl p-4 shadow-md border-2 border-primary/20">
                              <div className="w-12 h-12 bg-primary rounded-lg flex items-center justify-center text-white font-bold text-xl">
                                {dayIndex + 1}
                              </div>
                              <div>
                                <h4 className="font-bold text-lg">{day.date}</h4>
                                <div className="flex items-center gap-2 mt-1">
                                  <Badge variant="secondary" className="text-xs">
                                    {day.activities.filter(a => a.completed).length}/{day.activities.length} done
                                  </Badge>
                                  <span className="text-xs text-muted-foreground">
                                    {day.activities.length} activities
                                  </span>
                                </div>
                              </div>
                            </div>
                            <div className="flex-1 h-px bg-linear-to-r from-primary/30 to-transparent"></div>
                          </div>

                          {/* Activities Grid */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pl-4">
                            {day.activities.map((activity, actIdx) => (
                              <div key={activity.id} className="relative">
                                {/* Timeline connector */}
                                {actIdx > 0 && activity.travelTimeFromPrevious && (
                                  <div className="absolute -top-3 left-0 right-0 flex items-center justify-center">
                                    <div className="flex items-center gap-1.5 bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full text-xs">
                                      <Navigation className="w-3 h-3" />
                                      <span>{activity.travelTimeFromPrevious} min</span>
                                    </div>
                                  </div>
                                )}
                                
                                <div
                                  draggable
                                  onDragStart={() => handleDragStart(dayIndex, activity.id)}
                                  onDragOver={handleDragOver}
                                  onDrop={() => handleDrop(dayIndex, actIdx)}
                                  className={`p-4 rounded-xl border-2 transition-all cursor-move group h-full ${
                                    activity.completed
                                      ? 'bg-green-50 border-green-300 shadow-sm'
                                      : 'bg-white border-gray-200 hover:border-primary hover:shadow-lg'
                                  }`}
                                >
                                  <div className="flex items-start gap-3">
                                    {/* Drag Handle */}
                                    <div className="cursor-grab active:cursor-grabbing text-gray-400 hover:text-primary">
                                      <GripVertical className="w-4 h-4" />
                                    </div>
                                    
                                    {/* Activity Image */}
                                    {activity.image_url && (
                                      <img 
                                        src={activity.image_url} 
                                        alt={activity.title}
                                        className="w-16 h-16 rounded-lg object-cover shrink-0"
                                      />
                                    )}
                                    
                                    <div className="flex-1 min-w-0">
                                      <div className="flex items-center justify-between gap-2 mb-2">
                                        <div className="flex items-center gap-2">
                                          <Clock className="w-4 h-4 text-primary" />
                                          <span className="font-bold text-sm text-primary">{activity.time}</span>
                                          {activity.slotType && (
                                            <Badge variant="outline" className="text-[10px]">
                                              {activity.slotType}
                                            </Badge>
                                          )}
                                        </div>
                                        <div className="flex items-center gap-2">
                                          <button
                                            onClick={(e) => {
                                              e.stopPropagation();
                                              removeActivity(dayIndex, activity.id);
                                            }}
                                            className="p-1 hover:bg-red-50 hover:text-red-500 rounded transition-colors"
                                            title="Remove activity"
                                          >
                                            <X className="w-4 h-4" />
                                          </button>
                                          <div
                                            onClick={(e) => {
                                              e.stopPropagation();
                                              toggleActivity(dayIndex, activity.id);
                                            }}
                                            className={`w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 transition-colors cursor-pointer ${
                                              activity.completed
                                                ? 'bg-green-500 border-green-500'
                                                : 'border-gray-300 hover:border-primary'
                                            }`}
                                          >
                                            {activity.completed && <Check className="w-3.5 h-3.5 text-white stroke-3" />}
                                          </div>
                                        </div>
                                      </div>
                                      
                                      <h5 className={`font-semibold text-base leading-tight mb-2 ${activity.completed ? 'line-through text-muted-foreground' : 'text-gray-900'}`}>
                                        {activity.title}
                                      </h5>
                                      
                                      {activity.rating && (
                                        <div className="flex items-center gap-2 mb-2">
                                          <div className="flex items-center gap-1">
                                            <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                                            <span className="text-sm font-bold text-gray-700">{activity.rating}</span>
                                          </div>
                                          {activity.price && (
                                            <span className="text-sm text-gray-500">{activity.price}</span>
                                          )}
                                        </div>
                                      )}
                                      
                                      {activity.categories && activity.categories.length > 0 && (
                                        <div className="flex flex-wrap gap-1">
                                          {activity.categories.slice(0, 2).map((cat, i) => (
                                            <span key={i} className="text-[10px] bg-gray-100 text-gray-600 px-2 py-1 rounded-md font-medium">
                                              {cat}
                                            </span>
                                          ))}
                                        </div>
                                      )}
                                    </div>
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>

                          {day.activities.length === 0 && (
                            <div className="text-center py-12 text-muted-foreground bg-white rounded-xl border-2 border-dashed border-gray-200">
                              <p className="text-sm">No activities planned for this day</p>
                            </div>
                          )}

                          {/* Add Activity Button */}
                          <div className="pl-4 mt-4">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => setAddActivityModal({ open: true, dayIndex })}
                              className="gap-2"
                            >
                              <Plus className="w-4 h-4" />
                              Add Activity
                            </Button>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </div>
                </Card>
              </motion.div>
            )}

            {/* List View */}
            {viewMode === 'list' && days.map((day, dayIndex) => (
              <motion.div
                key={dayIndex}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: dayIndex * 0.1 }}
              >
                <Card className="p-6">
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                      <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
                        <CalendarIcon className="w-6 h-6 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-bold text-xl">{day.date}</h3>
                        <Badge variant="secondary" className="mt-1">
                          {day.activities.filter(a => a.completed).length}/{day.activities.length} completed
                        </Badge>
                      </div>
                    </div>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="gap-2"
                      onClick={() => setAddActivityModal({ open: true, dayIndex })}
                    >
                      <Plus className="w-4 h-4" />
                      Add Activity
                    </Button>
                  </div>

                  <div className="space-y-4">
                    {day.activities.map((activity, actIndex) => (
                      <div key={activity.id}>
                        {actIndex > 0 && activity.travelTimeFromPrevious && (
                          <div className="flex items-center gap-2 py-2 pl-8 text-xs text-muted-foreground">
                            <Navigation className="w-3 h-3" />
                            <span>{activity.travelTimeFromPrevious} min travel time</span>
                          </div>
                        )}
                        
                        <div
                          draggable
                          onDragStart={() => handleDragStart(dayIndex, activity.id)}
                          onDragOver={handleDragOver}
                          onDrop={() => handleDrop(dayIndex, actIndex)}
                          className={`flex items-start gap-4 p-4 rounded-lg border transition-all cursor-move ${
                            activity.completed
                              ? 'bg-green-50 border-green-200'
                              : 'bg-white border-border hover:border-primary/30 hover:shadow-sm'
                          }`}
                        >
                          {/* Drag Handle */}
                          <div className="cursor-grab active:cursor-grabbing text-gray-400 hover:text-primary mt-1">
                            <GripVertical className="w-5 h-5" />
                          </div>
                          
                          <button
                            onClick={() => toggleActivity(dayIndex, activity.id)}
                            className={`mt-1 w-6 h-6 rounded border-2 flex items-center justify-center transition-colors shrink-0 ${
                              activity.completed
                                ? 'bg-green-500 border-green-500'
                                : 'border-gray-300 hover:border-primary'
                            }`}
                          >
                            {activity.completed && <Check className="w-4 h-4 text-white" />}
                          </button>

                          {activity.image_url && (
                            <img 
                              src={activity.image_url} 
                              alt={activity.title}
                              className="w-20 h-20 rounded-lg object-cover shrink-0"
                            />
                          )}

                          <div className="flex-1 min-w-0">
                            <div className="flex items-start justify-between gap-2">
                              <div className={activity.completed ? 'line-through text-muted-foreground' : ''}>
                                <div className="flex items-center gap-2">
                                  <span className="font-semibold text-lg">{activity.title}</span>
                                  {activity.slotType && (
                                    <Badge variant="secondary" className="text-xs">{activity.slotType}</Badge>
                                  )}
                                </div>
                                
                                {activity.rating && (
                                  <div className="flex items-center gap-2 mt-1">
                                    <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                                    <span className="text-sm font-medium">{activity.rating}</span>
                                    {activity.price && (
                                      <span className="text-sm text-muted-foreground">{activity.price}</span>
                                    )}
                                  </div>
                                )}
                                
                                <div className="flex flex-wrap items-center gap-4 mt-2 text-sm text-muted-foreground">
                                  <span className="flex items-center gap-1.5">
                                    <Clock className="w-4 h-4" />
                                    {activity.time}
                                  </span>
                                  <span className="flex items-center gap-1.5">
                                    <MapPin className="w-4 h-4" />
                                    {activity.location}
                                  </span>
                                </div>
                                {activity.address && (
                                  <p className="text-xs text-muted-foreground mt-1">{activity.address}</p>
                                )}
                                {activity.categories && activity.categories.length > 0 && (
                                  <div className="flex flex-wrap gap-1 mt-2">
                                    {activity.categories.slice(0, 3).map((cat, i) => (
                                      <span key={i} className="text-xs bg-gray-100 px-2 py-0.5 rounded">{cat}</span>
                                    ))}
                                  </div>
                                )}
                              </div>
                              <button
                                onClick={() => removeActivity(dayIndex, activity.id)}
                                className="p-1.5 hover:bg-red-50 hover:text-red-500 rounded transition-colors shrink-0"
                              >
                                <X className="w-4 h-4" />
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}

                    {day.activities.length === 0 && (
                      <div className="text-center py-12 text-muted-foreground">
                        <p className="text-sm">No activities planned for this day</p>
                      </div>
                    )}
                  </div>
                </Card>
              </motion.div>
            ))}

            <Button variant="outline" onClick={addDay} className="w-full gap-2">
              <Plus className="w-4 h-4" />
              Add Another Day
            </Button>
          </div>
        )}
      </main>

      {/* Generate/Regenerate Itinerary Modal */}
      <GenerateItineraryModal
        open={showRegenerateModal}
        onOpenChange={setShowRegenerateModal}
        onGenerate={generateItinerary}
        isGenerating={isGenerating}
        currentDays={days.length}
        isRegenerate={days.length > 0}
      />

      {/* Add Activity Dialog */}
      <Dialog open={addActivityModal.open} onOpenChange={(open) => {
        setAddActivityModal({ open, dayIndex: null });
        if (!open) {
          setActivityMode('saved');
          setSelectedBusiness(null);
          setSearchQuery('');
        }
      }}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add Activity</DialogTitle>
            <DialogDescription>
              Add to Day {addActivityModal.dayIndex !== null ? addActivityModal.dayIndex + 1 : ''}
            </DialogDescription>
          </DialogHeader>

          {/* Mode Toggle */}
          <Tabs value={activityMode} onValueChange={(v) => setActivityMode(v as 'saved' | 'custom')}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="saved">From Saved Places</TabsTrigger>
              <TabsTrigger value="custom">Custom Activity</TabsTrigger>
            </TabsList>
          </Tabs>

          <div className="space-y-4 py-4">
            {activityMode === 'saved' ? (
              <>
                {/* Search Saved Places */}
                <div className="space-y-2">
                  <Label>Search Places</Label>
                  <Input
                    placeholder="Search from your saved places..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>

                {/* Places List */}
                <div className="space-y-2 max-h-96 overflow-y-auto">
                  {cachedBusinesses
                    .filter(b => 
                      b.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                      b.categories?.some((c: any) => c.title.toLowerCase().includes(searchQuery.toLowerCase()))
                    )
                    .slice(0, 10)
                    .map((business) => (
                      <div
                        key={business.id}
                        onClick={() => setSelectedBusiness(business)}
                        className={`p-3 rounded-lg border-2 cursor-pointer transition-all ${
                          selectedBusiness?.id === business.id
                            ? 'border-primary bg-primary/5'
                            : 'border-gray-200 hover:border-primary/50'
                        }`}
                      >
                        <div className="flex items-start gap-3">
                          {business.image_url && (
                            <img 
                              src={business.image_url} 
                              alt={business.name}
                              className="w-16 h-16 rounded-lg object-cover"
                            />
                          )}
                          <div className="flex-1 min-w-0">
                            <h4 className="font-semibold text-sm">{business.name}</h4>
                            <div className="flex items-center gap-2 mt-1">
                              <Star className="w-3 h-3 fill-yellow-400 text-yellow-400" />
                              <span className="text-xs font-medium">{business.rating}</span>
                              {business.price && (
                                <span className="text-xs text-gray-500">{business.price}</span>
                              )}
                            </div>
                            {business.categories && (
                              <p className="text-xs text-muted-foreground mt-1">
                                {business.categories.map((c: any) => c.title).join(', ')}
                              </p>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  {cachedBusinesses.length === 0 && (
                    <p className="text-sm text-muted-foreground text-center py-8">
                      No saved places available. Go to the dashboard to discover places first.
                    </p>
                  )}
                </div>

                {/* Time Selection */}
                <div className="space-y-2">
                  <Label htmlFor="saved-time">Time</Label>
                  <Input
                    id="saved-time"
                    type="time"
                    value={newActivity.time}
                    onChange={(e) => setNewActivity({ ...newActivity, time: e.target.value })}
                  />
                </div>
              </>
            ) : (
              <>
                {/* Custom Activity Form */}
                <div className="space-y-2">
                  <Label htmlFor="activity-title">Activity Name</Label>
                  <Input
                    id="activity-title"
                    placeholder="e.g., Visit Local Market"
                    value={newActivity.title}
                    onChange={(e) => setNewActivity({ ...newActivity, title: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="activity-time">Time</Label>
                  <Input
                    id="activity-time"
                    type="time"
                    value={newActivity.time}
                    onChange={(e) => setNewActivity({ ...newActivity, time: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="activity-location">Location (optional)</Label>
                  <Input
                    id="activity-location"
                    placeholder="e.g., Downtown"
                    value={newActivity.location}
                    onChange={(e) => setNewActivity({ ...newActivity, location: e.target.value })}
                  />
                </div>
              </>
            )}
          </div>

          <div className="flex gap-2 justify-end">
            <Button variant="outline" onClick={() => {
              setAddActivityModal({ open: false, dayIndex: null });
              setActivityMode('saved');
              setSelectedBusiness(null);
              setSearchQuery('');
            }}>
              Cancel
            </Button>
            <Button 
              onClick={handleAddActivity} 
              disabled={activityMode === 'saved' ? !selectedBusiness : !newActivity.title}
            >
              Add Activity
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
